version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - fonts-liberation
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
