version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - fonts-liberation
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  builder: dirhtml
