codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: false
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
